BEGIN;

    CREATE TABLE TASK (
        id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
        assigned_user_id UUID REFERENCES PROFILE (id) ON DELETE SET NULL ON UPDATE RESTRICT
    );

    CREATE TABLE WORK_TIME (
        id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
        task_id UUID NOT NULL REFERENCES TASK (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
        milliseconds INTEGER NOT NULL,
        timestamp TIMESTAMP WITH TIME ZONE NOT NULL
    );

    CREATE TABLE WORK_TIMER (
        id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
        task_id UUID NOT NULL REFERENCES TASK (id) ON DELETE CASCADE ON UPDATE RESTRICT,
        user_id UUID NOT NULL UNIQUE REFERENCES PROFILE (id) ON DELETE CASCADE ON UPDATE RESTRICT,
        timestamp_start TIMESTAMP WITH TIME ZONE NOT NULL
    );

    COMMIT;
END;